# -*- coding: utf-8 -*-
"""fakenote_detection_decisiontree&random_forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PIeyLdDSHi2KzRJAHd12rqZumvxGiueZ
"""

import numpy as np
import pandas as pd

data=pd.read_csv("/content/BankNoteAuthentication.csv")

data.head()

x=data.drop(['class'],axis=1)
y=data['class']

x.head()

data.describe()

data.info()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

"""Decision Trees"""

from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()

tree.fit(x_train,y_train)

tree_predictions=tree.predict(x_test)

#accuracy of decision tree model
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,tree_predictions)
ac=accuracy_score(y_test,tree_predictions)

print(cm)

print(ac)

"""Random Forest"""

from sklearn.ensemble import RandomForestClassifier
random_forest=RandomForestClassifier()

random_forest.fit(x_train,y_train)

forest_predictions=random_forest.predict(x_test)

#accuracy of random forest model
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,forest_predictions)
ac=accuracy_score(y_test,forest_predictions)

print(cm)

print(ac)