# -*- coding: utf-8 -*-
"""Persistent_sp_LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENTGIxTl6FQQRtR8Ri2vAtFeVS30eGyP
"""

import pandas as pd
import matplotlib as mlt
import numpy as np
import seaborn as snr

data=pd.read_csv("/content/sample_data/Persistent data set-2.csv")

data.info()
data.head()

d=data.iloc[0:300].plot(figsize=(8,3), title="Persistent")
d.set_xlabel("Day")
d.set_ylabel("Value")

data.iloc[0:21]['Value'].diff().plot(kind="bar")      # histogram

data.iloc[0:9].plot(figsize=(8,8),kind='bar')

piedata=data.drop(['Date'],axis=1)

data.dtypes
# data['Date']=pd.to_datetime(data['Date'])

piedata.plot.pie(figsize=(10,10),fontsize=15,autopct='%.2f',subplots=True) # need to explain

piedata.iloc[0:3].plot.pie(subplots=True)      #need to explain

data.info()



predata=data.drop(['Date'],axis=1)

x=predata[['nifty-50','Sensex']]
y=predata[['Value']]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

x_train.shape

y_train.shape

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

lregression=LinearRegression()
dregression=DecisionTreeRegressor()

lregression.fit(x_train,y_train)

dregression.fit(x_train,y_train)

lregression.score(x,y)

dregression.score(x,y)

"""#26/12/2022 data of sensex and nifty-50"""

lregression.predict([[17993,60495.27]])

dregression.predict([[17993,60495.27]])

