# -*- coding: utf-8 -*-
"""kmeans_clustering (4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kBDSaHQrBOmdO3PV0qWWHYWjY_5LyHkr
"""

import numpy as np
import pandas as pd

data=pd.read_csv("/content/3.01. Country clusters.csv")

data.head(10)

new_data=data.iloc[:,1:3] #all the rows for 1st and 2nd column

new_data.head()

from sklearn.cluster import KMeans

kmeans=KMeans(3) #here 3 indicates the number of clusters

kmeans.fit(new_data) #training takes place with the entire data we have

identified_clusters=kmeans.fit_predict(new_data)

identified_clusters

